### ISSUE TITLE
corrupted zip

### ISSUE THREAD

**Issue by jlavoieqc** [katlol/awesome-flipperzero-pack#2]
The released sdcard zip is corrupted

**Comment by Orphan-Crippler** [comment]
I ran the script locally and it worked for me.

**Comment by jlavoieqc** [comment]
I mean its github actions release so i think its fixed

**Comment by iakat** [comment]
@jlavoieqc thank you for your report and sorry that happened. could you post some details, like which zip you downloaded and what error you got how?

I am adding something to remove old zips so it's possible it will get removed, but perhaps if we can reproduce this issue I can try preventing it in the future.

**Comment by jlavoieqc** [comment]
@katlol Dont remember but i think its https://github.com/katlol/awesome-flipperzero-pack/releases/tag/v0.0.202402100235

**Comment by jlavoieqc** [comment]
> @jlavoieqc thank you for your report and sorry that happened. could you post some details, like which zip you downloaded and what error you got how?
> 
> I am adding something to remove old zips so it's possible it will get removed, but perhaps if we can reproduce this issue I can try preventing it in the future.

I just tried to open it in explorer windows but it said corrupted

**Comment by iakat** [comment]
I downloaded and tested all the files in the release you linked

```
for i in $(ls awesome-flipperzero-pack-v0.0.202402100235-*); do echo md5sum $i; unzip -t $i | grep -v OK$; echo ---; done
md5sum awesome-flipperzero-pack-v0.0.202402100235-microsd-wavplayer.zip
Archive:  awesome-flipperzero-pack-v0.0.202402100235-microsd-wavplayer.zip
No errors detected in compressed data of awesome-flipperzero-pack-v0.0.202402100235-microsd-wavplayer.zip.
---
md5sum awesome-flipperzero-pack-v0.0.202402100235-microsd.zip
Archive:  awesome-flipperzero-pack-v0.0.202402100235-microsd.zip
No errors detected in compressed data of awesome-flipperzero-pack-v0.0.202402100235-microsd.zip.
---
md5sum awesome-flipperzero-pack-v0.0.202402100235-tweaks.zip
Archive:  awesome-flipperzero-pack-v0.0.202402100235-tweaks.zip
No errors detected in compressed data of awesome-flipperzero-pack-v0.0.202402100235-tweaks.zip.
---
```

and all 3 zip files tested successfully.

Is it possible it was a bad download? If you still have the file, or maybe in your browser history you have an entry, and it's a different file I can check those too

**Comment by jlavoieqc** [comment]
> I downloaded and tested all the files in the release you linked
> 
> ```
> for i in $(ls awesome-flipperzero-pack-v0.0.202402100235-*); do echo md5sum $i; unzip -t $i | grep -v OK$; echo ---; done
> md5sum awesome-flipperzero-pack-v0.0.202402100235-microsd-wavplayer.zip
> Archive:  awesome-flipperzero-pack-v0.0.202402100235-microsd-wavplayer.zip
> No errors detected in compressed data of awesome-flipperzero-pack-v0.0.202402100235-microsd-wavplayer.zip.
> ---
> md5sum awesome-flipperzero-pack-v0.0.202402100235-microsd.zip
> Archive:  awesome-flipperzero-pack-v0.0.202402100235-microsd.zip
> No errors detected in compressed data of awesome-flipperzero-pack-v0.0.202402100235-microsd.zip.
> ---
> md5sum awesome-flipperzero-pack-v0.0.202402100235-tweaks.zip
> Archive:  awesome-flipperzero-pack-v0.0.202402100235-tweaks.zip
> No errors detected in compressed data of awesome-flipperzero-pack-v0.0.202402100235-tweaks.zip.
> ---
> ```
> 
> and all 3 zip files tested successfully.
> 
> Is it possible it was a bad download? If you still have the file, or maybe in your browser history you have an entry, and it's a different file I can check those too

I dont know but I tried to download it 2 times but corrupted i think they are no longer availible

**Comment by iakat** [comment]
OK, feel free to reopen if you know what file it was or it happens again.
